import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { ModalProvider } from '@/context/modalContext';
import { AuthLayout } from './AuthLayout';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ModalProvider>
					<AuthLayout>{children}</AuthLayout>
				</ModalProvider>
				<ToastContainer />
			</body>
		</html>
	);
}
